name: Compile document

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/huangfusl/template:v2.7.0
    permissions:
      contents: write
    steps:
      - name: Checkout tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Compile pgf images
        run: |
          find . -name "*.py" -exec python3 {} \;

      - name: Compile PDF and compress
        run: |
          ln -s /opt/template/makefile.latex.template makefile.latex.template
          make default
          find ./lec[0-9] \( -name "*.pdf" -o -name "*.ipynb" \) -exec tar -czvf lec_files.tar.gz {} +

      - name: Update release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lec_files.tar.gz
